language: php
php:
  - '7.4'

install:
  - composer install

script:
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpstan analyse
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpcs -s

after_success:
  - travis_retry php vendor/bin/php-coveralls